from typing import Any

import numpy as np


def rational_array(data: Any, denominator: Any = None) -> "RationalArray": ...


class RationalArray(np.ndarray):
    def __add__(self, other: Any) -> "RationalArray": ...
    def __mul__(self, other: Any) -> "RationalArray": ...
    def __getitem__(self, index: Any) -> Any: ...
